nome = str (input("Digite seu nome completo:")).strip()
dividido = nome.split()
print("MUito prazer em conhece-lo!")
print("Seu primeiro nome é: {}".format(dividido[0]))
print("Seu ultimo nome é: {}".format(dividido[len(dividido)-1]))
